services:
  compactions-api:
    build:
      context: ./deploy
      dockerfile: Dockerfile
    container_name: compactions-api
    ports:
      - "8000:8000"
    volumes:
      - ./compactions-api:/compactions-api
    environment:
      - DATABASE_URL=mysql+pymysql://ruvs:Emmtp157@10.1.75.157:3306/ruvs
    command: ["sh", "-c", "python main.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]
