DISTRITOS = [
    {"renglon": 1, "municipio": "PILAR"},
    {"renglon": 1, "municipio": "GENERAL SAN MARTÍN"},
    {"renglon": 1, "municipio": "JOSÉ C. PAZ"},
    {"renglon": 1, "municipio": "MALVINAS ARGENTINAS"},
    {"renglon": 1, "municipio": "CAMPANA"},
    {"renglon": 1, "municipio": "ESCOBAR"},
    {"renglon": 1, "municipio": "TIGRE"},
    {"renglon": 1, "municipio": "SAN FERNANDO"},
    {"renglon": 1, "municipio": "ZÁRATE"},
    {"renglon": 1, "municipio": "EXALT. DE LA CRUZ"},
    {"renglon": 1, "municipio": "SAN MIGUEL"},
    {"renglon": 1, "municipio": "TRES DE FEBRERO"},
    {"renglon": 1, "municipio": "VICENTE LÓPEZ"},
    {"renglon": 1, "municipio": "SAN ISIDRO"},
    {"renglon": 1, "municipio": "BARADERO"},
    {"renglon": 1, "municipio": "SAN PEDRO"},
    {"renglon": 1, "municipio": "RAMALLO"},
    {"renglon": 1, "municipio": "SAN NICOLÁS"},
    {"renglon": 1, "municipio": "PERGAMINO"},
    {"renglon": 1, "municipio": "COLÓN"},
    {"renglon": 1, "municipio": "ROJAS"},
    {"renglon": 1, "municipio": "SALTO"},
    {"renglon": 1, "municipio": "CARMEN DE ARECO"},
    {"renglon": 1, "municipio": "SAN ANDRÉS DE GILES"},
    {"renglon": 1, "municipio": "SAN ANTONIO DE ARECO"},
    {"renglon": 1, "municipio": "CAPITÁN SARMIENTO"},
    {"renglon": 1, "municipio": "ARRECIFES"},
    {"renglon": 2, "municipio": "LA MATANZA"},
    {"renglon": 2, "municipio": "MORÓN"},
    {"renglon": 2, "municipio": "HURLINGHAM"},
    {"renglon": 2, "municipio": "ITUZAINGÓ"},
    {"renglon": 2, "municipio": "MERLO"},
    {"renglon": 2, "municipio": "MORENO"},
    {"renglon": 2, "municipio": "MARCOS PAZ"},
    {"renglon": 2, "municipio": "GENERAL LAS HERAS"},
    {"renglon": 2, "municipio": "GENERAL RODRÍGUEZ"},
    {"renglon": 2, "municipio": "LUJÁN"},
    {"renglon": 2, "municipio": "LAS FLORES"},
    {"renglon": 2, "municipio": "TAPALQUÉ"},
    {"renglon": 2, "municipio": "AZUL"},
    {"renglon": 2, "municipio": "BENITO JUÁREZ"},
    {"renglon": 2, "municipio": "LAPRIDA"},
    {"renglon": 2, "municipio": "GENERAL LA MADRID"},
    {"renglon": 2, "municipio": "OLAVARRÍA"},
    {"renglon": 2, "municipio": "BOLIVAR"},
    {"renglon": 2, "municipio": "DAIREAUX"},
    {"renglon": 2, "municipio": "GUAMINÍ"},
    {"renglon": 2, "municipio": "ADOLFO ALSINA"},
    {"renglon": 2, "municipio": "SALLIQUELÓ"},
    {"renglon": 2, "municipio": "TRES LOMAS"},
    {"renglon": 2, "municipio": "PELLEGRINI"},
    {"renglon": 2, "municipio": "TRENQUE LAUQUEN"},
    {"renglon": 2, "municipio": "RIVADAVIA"},
    {"renglon": 2, "municipio": "CARLOS TEJEDOR"},
    {"renglon": 2, "municipio": "PEHUAJÓ"},
    {"renglon": 2, "municipio": "HIPÓLITO YRIGOYEN"},
    {"renglon": 2, "municipio": "CARLOS CASARES"},
    {"renglon": 2, "municipio": "NUEVE DE JULIO"},
    {"renglon": 2, "municipio": "LINCOLN"},
    {"renglon": 2, "municipio": "FLORENTINO AMEGHINO"},
    {"renglon": 2, "municipio": "GENERAL PINTO"},
    {"renglon": 2, "municipio": "GENERAL VILLEGAS"},
    {"renglon": 2, "municipio": "LEANDRO N. ALEM"},
    {"renglon": 2, "municipio": "GENERAL ARENALES"},
    {"renglon": 2, "municipio": "JUNÍN"},
    {"renglon": 2, "municipio": "GENERAL VIAMONTE"},
    {"renglon": 2, "municipio": "GENERAL ALVEAR"},
    {"renglon": 2, "municipio": "SALADILLO"},
    {"renglon": 2, "municipio": "ROQUE PEREZ"},
    {"renglon": 2, "municipio": "RAUCH"},
    {"renglon": 2, "municipio": "TANDIL"},
    {"renglon": 3, "municipio": "BERISSO"},
    {"renglon": 3, "municipio": "ENSENADA"},
    {"renglon": 3, "municipio": "LA PLATA"},
    {"renglon": 3, "municipio": "LA COSTA"},
    {"renglon": 3, "municipio": "PINAMAR"},
    {"renglon": 3, "municipio": "VILLA GESELL"},
    {"renglon": 3, "municipio": "MAR CHIQUITA"},
    {"renglon": 3, "municipio": "GENERAL PUEYRREDÓN"},
    {"renglon": 3, "municipio": "GENERAL ALVARADO"},
    {"renglon": 3, "municipio": "LOBERÍA"},
    {"renglon": 3, "municipio": "NECOCHEA"},
    {"renglon": 3, "municipio": "SAN CAYETANO"},
    {"renglon": 3, "municipio": "BALCARCE"},
    {"renglon": 3, "municipio": "AYACUCHO"},
    {"renglon": 3, "municipio": "GENERAL GUIDO"},
    {"renglon": 3, "municipio": "DOLORES"},
    {"renglon": 3, "municipio": "TORDILLO"},
    {"renglon": 3, "municipio": "GENERAL LAVALLE"},
    {"renglon": 3, "municipio": "GENERAL MADARIAGA"},
    {"renglon": 3, "municipio": "MAIPÚ"},
    {"renglon": 3, "municipio": "PILA"},
    {"renglon": 3, "municipio": "CASTELLI"},
    {"renglon": 3, "municipio": "LEZAMA"},
    {"renglon": 3, "municipio": "CHASCOMÚS"},
    {"renglon": 3, "municipio": "PUNTA INDIO"},
    {"renglon": 3, "municipio": "MAGDALENA"},
    {"renglon": 3, "municipio": "BRANDSEN"},
    {"renglon": 3, "municipio": "GENERAL PAZ"},
    {"renglon": 3, "municipio": "SAN VICENTE"},
    {"renglon": 3, "municipio": "CAÑUELAS"},
    {"renglon": 3, "municipio": "PRESIDENTE PERÓN"},
    {"renglon": 3, "municipio": "GENERAL BELGRANO"},
    {"renglon": 3, "municipio": "MONTE"},
    {"renglon": 3, "municipio": "LOBOS"},
    {"renglon": 3, "municipio": "NAVARRO"},
    {"renglon": 3, "municipio": "VEINTICINCO DE MAYO"},
    {"renglon": 3, "municipio": "ALBERTI"},
    {"renglon": 3, "municipio": "BRAGADO"},
    {"renglon": 3, "municipio": "CHACABUCO"},
    {"renglon": 3, "municipio": "CHIVILCOY"},
    {"renglon": 3, "municipio": "SUIPACHA"},
    {"renglon": 3, "municipio": "MERCEDES"},
    {"renglon": 4, "municipio": "ALMIRANTE BROWN"},
    {"renglon": 4, "municipio": "BERAZATEGUI"},
    {"renglon": 4, "municipio": "AVELLANEDA"},
    {"renglon": 4, "municipio": "LANÚS"},
    {"renglon": 4, "municipio": "EZEIZA"},
    {"renglon": 4, "municipio": "LOMAS DE ZAMORA"},
    {"renglon": 4, "municipio": "QUILMES"},
    {"renglon": 4, "municipio": "ESTEBAN ECHEVERRÍA"},
    {"renglon": 4, "municipio": "CORONEL ROSALES"},
    {"renglon": 4, "municipio": "MONTE HERMOSO"},
    {"renglon": 4, "municipio": "CORONEL DORREGO"},
    {"renglon": 4, "municipio": "TRES ARROYOS"},
    {"renglon": 4, "municipio": "ADOLFO GONZALES CHAVES"},
    {"renglon": 4, "municipio": "CORONEL PRINGLES"},
    {"renglon": 4, "municipio": "CORONEL SUAREZ"},
    {"renglon": 4, "municipio": "SAAVEDRA"},
    {"renglon": 4, "municipio": "PUÁN"},
    {"renglon": 4, "municipio": "TORNQUIST"},
    {"renglon": 4, "municipio": "BAHÍA BLANCA"},
    {"renglon": 4, "municipio": "VILLARINO"},
    {"renglon": 4, "municipio": "PATAGONES"},
    {"renglon": 4, "municipio": "FLORENCIO VARELA"},
]